export const filmsMock = [
  {
    id: 1,
    imgUrl: 'assets/img/Marvel1.jpg',
    movieName: 'Marvel One-Shot: Item 47',
    releaseYear: 2012,
    isFavourite: false,
    description: 'The best movie ever!',
  },
  {
    id: 2,
    imgUrl: 'assets/img/Marvel2.jpg',
    movieName: 'Captain Marvel',
    releaseYear: 2019,
    isFavourite: false,
    description: 'The best movie ever!',
  },
  {
    id: 3,
    imgUrl: 'assets/img/Marvel3.jpg',
    movieName: 'Marvel Studios: Legends',
    releaseYear: 2021,
    isFavourite: false,
    description: 'The best movie ever!',
  },
  {
    id: 4,
    imgUrl: 'assets/img/Marvel4.jpg',
    movieName: 'Marvel One-Shot: The Consultant',
    releaseYear: 2011,
    isFavourite: false,
    description: 'The best movie ever!',
  },
  {
    id: 5,
    imgUrl: 'assets/img/Marvel5.jpg',
    movieName: 'Marvel Studios: Assembled',
    releaseYear: 2021,
    isFavourite: false,
    description: 'The best movie ever!',
  },
  {
    id: 6,
    imgUrl: 'assets/img/Marvel6.jpg',
    movieName: 'Lego Marvel Super Heroes',
    releaseYear: 2013,
    isFavourite: false,
    description: 'The best movie ever!',
  },
  {
    id: 7,
    imgUrl: 'assets/img/Marvel7.jpg',
    movieName: "Marvel One-Shot: A Funny Thing Happened on the Way to Thor's Hammer",
    releaseYear: 2011,
    isFavourite: false,
    description: 'The best movie ever!',
  },
  {
    id: 8,
    imgUrl: 'assets/img/Marvel8.jpg',
    movieName: 'Marvel One-Shot: Agent Carter',
    releaseYear: 2013,
    isFavourite: false,
    description: 'The best movie ever!',
  },
  {
    id: 9,
    imgUrl: 'assets/img/Marvel9.jpg',
    movieName: 'Marvel One-Shot: All Hail the King',
    releaseYear: 2014,
    isFavourite: false,
    description: 'The best movie ever!',
  },
  {
    id: 10,
    imgUrl: 'assets/img/Marvel10.jpg',
    movieName: 'Marvel Studios: Assembling a Universe',
    releaseYear: 2014,
    isFavourite: false,
    description: 'The best movie ever!',
  },
];
